spring:
  application:
    name: gateway-server
  boot:
    admin:
      context-path: /admin
  cloud:
    gateway:
      ## use service discovery as route
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8072
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
management:
  endpoint:
    gateway:
      enabled: true # default value
    web:
      exposure:
        include: gateway
